name: Deploy Studio

on:
  workflow_call:
    inputs:
      STUDIO_HOSTNAME:
        required: true
        type: string
      STUDIO_TITLE:
        required: true
        type: string

permissions:
  contents: read
  pull-requests: write

env:
  SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
  STUDIO_HOSTNAME: ${{ inputs.STUDIO_HOSTNAME }}

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.ref_name }}-deploy-studio"

jobs:
  deploy:
    defaults:
      run:
        working-directory: ./studio
    name: Deploy
    runs-on: ubuntu-22.04

    environment:
      name: Development
      url: ${{ steps.deploy.outputs.STUDIO_URL }}

    steps:
      - uses: actions/checkout@v4
      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: yarn
      - run: yarn install --immutable

      - name: Build and deploy Sanity Studio
        id: deploy
        env:
          SANITY_STUDIO_DATASET: ${{ vars.SANITY_STUDIO_DATASET }}
          SANITY_STUDIO_TITLE: ${{inputs.STUDIO_TITLE}}
          SANITY_STUDIO_HOSTNAME: ${{inputs.STUDIO_HOSTNAME}}

        run: |
          yarn deploy --yes --source-maps
          echo "STUDIO_URL=https://${SANITY_STUDIO_HOSTNAME}.sanity.studio" >> $GITHUB_OUTPUT

      - name: Post preview link
        uses: actions/github-script@v7
        with:
          script: |
            const body = [
              '**ðŸš€ Preview environment has been deployed!**',
              `Visit [${process.env.STUDIO_URL}](${process.env.STUDIO_URL}) to see your changes.`,
              "*This is a temporary environment that will be undeployed when this PR is merged or closed.*"
            ].join('\n\n')

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body,
            })
        env:
          STUDIO_URL: ${{ steps.deploy.outputs.STUDIO_URL }}
